### ISSUE TITLE
Loss of flow navigation while looping through calls to flows

### ISSUE THREAD

**Issue by jvanzyl** [concord-workflow/ck8s-cli#1]
In the following block we lose the ability to navigate to the flows listed in `items`

```
    - call: ${item}
      loop:
        mode: parallel
        parallelism: 5
        items:
          - "aepMysql"
          - "aepElasticsearch"
          - "aepMemcached"
          - "aepCognito"
          - "aepAthena"
```          

Would be nice to still navigate to the source flows listed in `items`.
