### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by ibodrov** [concord-workflow/ck8s-cli#17]
My personal wish list for ck8s-cli:

- [x] validate the flow name before starting the process. It's not great to wait for the process to start only to find out that I had misspelled the entry point
- [ ] a "lint" action to compile expressions and show any errors
- [x] colorized output a-la recent concord-cli versions
- [ ] be able to run a specific file using flow-executor=concord-cli (e.g. from a non-standard directory)
- [ ] warn about expressions in multi-line text blocks that include a `\n`. E.g.
  ```yaml
  configuration:
    runtime: "concord-v2"
  flows:
    default:
      - set:
          items:
            - foo
            - bar
      - set:
          newItems: ${items.stream().toList()}
          newItemsButWorse: |
            ${items.stream().toList()}
      - log: "${newItems.getClass()} /// ${newItemsButWorse.getClass()}"
    # outputs
    #   ArrayList /// String
    ```
